---
- name: Ensure dirs exists with correct perms
  file:
    dest: "{{ dirpath }}"
    state: directory
    owner: "{{ rclone_owner }}"
    group: "{{ rclone_group }}"
    recurse: no
  become: yes
  with_items:
    - "{{ rclone_src_dir }}"
    - "{{ rclone_bin_dir }}"
  loop_control:
    loop_var: dirpath

- name: install rclone - unzip package
  unarchive:
    src: https://github.com/ncw/rclone/releases/download/{{ rclone_version }}/{{ rclone_file }}.zip
    dest: "{{ rclone_src_dir}}"
    copy: no
    creates: '{{ rclone_src_dir}}/{{ rclone_file }}'
  become: yes

- name: install rclone - copy binary
  copy:
    src: "{{ rclone_src_dir}}/{{ rclone_file }}/rclone"
    dest: "{{ rclone_bin_dir }}/rclone"
    mode: 0755
    owner: "{{ rclone_owner }}"
    group: "{{ rclone_group }}"
    remote_src: true
  become: yes