---
- name: gather os specific variables
  include_vars: "{{ item }}"
  with_first_found:
    - '{{ ansible_distribution }}-{{ ansible_distribution_major_version}}.yml'
    - '{{ ansible_distribution }}.yml'
    - '{{ ansible_os_family }}.yml'
  tags:
    - vars

- name: Install required packages
  package:
    name: '{{ item }}'
    state: present
  become: yes
  with_items: '{{ rclone_packages }}'

- include_tasks: install.yml