---
- name: gather os specific variables
  include_vars: "{{ item }}"
  with_first_found:
    - '{{ ansible_distribution }}-{{ ansible_distribution_major_version}}.yml'
    - '{{ ansible_distribution }}.yml'
    - '{{ ansible_os_family }}.yml'
  tags:
    - vars

- name: Install required packages
  package:
    name: '{{ item }}'
    state: present
  become: yes
  with_items: '{{ rclone_packages }}'

- include_tasks: install.yml

- name: Install man pages
  block: 
    - name: install rclone - make dir for local manpages
      file:
        path: '{{ rclone_man_pages_path }}'
        state: directory
        mode: 0775
        owner: '{{ rclone_man_pages_owner }}'
        group: '{{ rclone_man_pages_group }}'
      become: yes

    - name: install rclone - copy manpage
      copy:
        src: "{{ rclone_src_dir}}/{{ rclone_file }}/rclone.1"
        dest: "{{ rclone_man_pages_path }}/rclone.1"
        mode: 0644
        owner: root
        group: root
        remote_src: true
      notify: update mandb
      become: yes
  when: rclone_man_pages_install
